version: "3"
services:
  spark:
    #image: docker.io/bitnami/spark:3.3
    build: docker/spark/.
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7070:7070'
    volumes:
      - ./shared_core:/shared_core
      - ./shared_usr:/shared_usr

  spark-worker:
    #image: docker.io/bitnami/spark:3.3
    build: docker/spark/.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./shared_core:/shared_core
      - ./shared_usr:/shared_usr
    ports:
      - '8081:8080'

  zookeeper:
    image: 'bitnami/zookeeper:3.6.4'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  input_kafka:
    image: 'bitnami/kafka:3.3.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  jupyter_notebook:
    image: 'jupyter/all-spark-notebook'
    ports: 
      - '8888:8888'
    volumes:
      - ./shared_core:/shared_core
      - ./shared_usr:/shared_usr
  
  # output_kafka:
  #   image: 'bitnami/kafka:3.3.1'
  #   ports:
  #     - '9093:9092'
  #   environment:
  #     - KAFKA_BROKER_ID=2
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper
