apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-deployment
  labels:
    app: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
        - name: jupyterlab
          image: jupyter/all-spark-notebook:python-3.10
          ports:
            - containerPort: 8888


