apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-service
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30100