apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-train
spec:
  type: Python
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: "/home/bubikhonza/mlpsuite/mlpsuite_infrastructure/shared/core/run_train_job.py"
  deps:
    files:
      - "/home/bubikhonza/mlpsuite/mlpsuite_infrastructure/shared/usr/dependencies.zip"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "shared-volume"
      hostPath:
        path: /home/bubikhonza/mlpsuite/mlpsuite_infrastructure/shared #this path is from minikubes docker volume mount
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
    volumeMounts:
      - name: "shared-volume"
        mountPath: "/shared"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "shared-volume"
        mountPath: "/shared"